name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Deploy on self-hosted runner
        run: |
          if [ ! -d /home/ubuntu/spotiplay ]; then
            git clone git@github.com:chubi-x/spotiplay /home/ubuntu/spotiplay;
          fi
          cd /home/ubuntu/spotiplay
          chmod +x deploy.sh
          ./deploy.sh

