name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy on self-hosted runner
        run: |
          cd /home/ubuntu/spotiplay
          chmod +x deploy.sh
          ./deploy.sh

