name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Deploy on self-hosted runner
        run: |
        [ ! -d '/home/ubuntu/spotiplay'] && git clone git@github.com:chubi-x/spotiplay /home/ubuntu/spotiplay
          cd /home/ubuntu/spotiplay
          chmod +x deploy.sh
          ./deploy.sh

